name: Python application

on: push

jobs:
  example-3:
    name: Test Nano Tips
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: reddit-tipbot
          environment-file: environment.yml
          python-version: 3.7
          condarc-file: condarc.yml
          auto-activate-base: false
      - name: Check conda
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Setup tipbot module
        shell: bash -l {0}
        run: |
          make module-setup
      - name: Pytest
        shell: bash -l {0}
        run: |
          make test
      - name: Black
        shell: bash -l {0}
        run: |
          make black
